name: anygrasp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.15.3
  - attr=2.5.2
  - binutils=2.45.1
  - binutils_impl_linux-64=2.45.1
  - binutils_linux-64=2.45.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-compiler=1.7.0
  - ca-certificates=2026.1.4
  - cairo=1.18.0
  - cmake=4.2.3
  - cuda-cccl=12.1.109
  - cuda-cccl-impl=2.0.1
  - cuda-cccl_linux-64=12.1.109
  - cuda-command-line-tools=12.1.1
  - cuda-compiler=12.1.1
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cudart-dev_linux-64=12.1.105
  - cuda-cudart-static=12.1.105
  - cuda-cudart-static_linux-64=12.1.105
  - cuda-cudart_linux-64=12.1.105
  - cuda-cuobjdump=12.1.111
  - cuda-cupti=12.1.105
  - cuda-cupti-dev=12.1.105
  - cuda-cuxxfilt=12.1.105
  - cuda-driver-dev=12.1.105
  - cuda-driver-dev_linux-64=12.1.105
  - cuda-gdb=12.1.105
  - cuda-libraries=12.1.1
  - cuda-libraries-dev=12.1.1
  - cuda-nsight=12.1.105
  - cuda-nvcc=12.1.105
  - cuda-nvcc-dev_linux-64=12.1.105
  - cuda-nvcc-impl=12.1.105
  - cuda-nvcc-tools=12.1.105
  - cuda-nvcc_linux-64=12.1.105
  - cuda-nvdisasm=12.1.105
  - cuda-nvml-dev=12.1.105
  - cuda-nvprof=12.1.105
  - cuda-nvprune=12.1.105
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-nvvp=12.1.105
  - cuda-opencl=12.1.105
  - cuda-opencl-dev=12.1.105
  - cuda-profiler-api=12.1.105
  - cuda-sanitizer-api=12.1.105
  - cuda-toolkit=12.1.1
  - cuda-tools=12.1.1
  - cuda-version=12.1
  - cuda-visual-tools=12.1.1
  - cxx-compiler=1.7.0
  - dbus=1.13.6
  - expat=2.7.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - gcc=12.4.0
  - gcc_impl_linux-64=12.4.0
  - gcc_linux-64=12.4.0
  - gds-tools=1.6.1.9
  - glib=2.84.0
  - glib-tools=2.84.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.4
  - gstreamer=1.24.4
  - gxx=12.4.0
  - gxx_impl_linux-64=12.4.0
  - gxx_linux-64=12.4.0
  - harfbuzz=9.0.0
  - icu=73.2
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - ld_impl_linux-64=2.45.1
  - libcap=2.77
  - libclang-cpp15=15.0.7
  - libclang13=19.1.2
  - libcublas=12.1.3.1
  - libcublas-dev=12.1.3.1
  - libcufft=11.0.2.54
  - libcufft-dev=11.0.2.54
  - libcufile=1.6.1.9
  - libcufile-dev=1.6.1.9
  - libcups=2.3.3
  - libcurand=10.3.2.106
  - libcurand-dev=10.3.2.106
  - libcurl=8.18.0
  - libcusolver=11.4.5.107
  - libcusolver-dev=11.4.5.107
  - libcusparse=12.1.0.106
  - libcusparse-dev=12.1.0.106
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.4
  - libffi=3.4.4
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=12.4.0
  - libgcc-ng=15.2.0
  - libglib=2.84.0
  - libgomp=15.2.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libllvm15=15.0.7
  - libllvm19=19.1.2
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libnghttp2=1.67.0
  - libnpp=12.1.0.40
  - libnpp-dev=12.1.0.40
  - libnsl=2.0.0
  - libnuma=2.0.18
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.2.0.2
  - libnvjpeg-dev=12.2.0.2
  - libogg=1.3.5
  - libopus=1.6.1
  - libpng=1.6.55
  - libpq=16.11
  - libsanitizer=12.4.0
  - libsndfile=1.2.2
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=12.4.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libuuid=2.41.3
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libxcb=1.15
  - libxkbcommon=1.7.0
  - libxkbfile=1.1.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - mkl=2025.2.0
  - mkl-include=2025.3.0
  - mpg123=1.32.9
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - ncurses=6.5
  - nsight-compute=2023.1.1.4
  - nspr=4.38
  - nss=3.118
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openssl=3.6.1
  - pcre2=10.44
  - pip=26.0.1
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pulseaudio-client=17.0
  - python=3.10.12
  - qt-main=5.15.8
  - readline=8.3
  - rhash=1.4.6
  - sqlite=3.51.1
  - sysroot_linux-64=2.34
  - tbb=2022.1.0
  - tk=8.6.13
  - wayland=1.23.1
  - wheel=0.46.3
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.42
  - xorg-compositeproto=0.4.2
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.5
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.5
  - xorg-randrproto=1.5.0
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.20.2
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xorgproto=2025.1
  - xorg-xproto=7.0.31
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - autolab-core==1.1.1
      - autolab-perception==1.0.0
      - blinker==1.9.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorlog==6.10.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cvxopt==1.3.3
      - cycler==0.12.1
      - cython==3.2.4
      - dash==4.0.0
      - decorator==5.2.1
      - dill==0.4.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - ffmpeg-python==0.2.0
      - filelock==3.20.0
      - flask==3.1.2
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - future==1.0.0
      - grasp-nms==1.0.2
      - graspnetapi==1.2.10
      - h5py==3.15.1
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - minkowskiengine==0.5.4
      - mpmath==1.3.0
      - multiprocess==0.70.19
      - narwhals==2.16.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - open3d==0.19.0
      - opencv-python==4.9.0.80
      - packaging==26.0
      - pandas==2.3.3
      - parso==0.8.6
      - pexpect==4.9.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - plotly==6.5.2
      - pointnet2==0.0.0
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.3.2
      - pyquaternion==0.9.9
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavefront==1.3.3
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - retrying==1.4.2
      - rpds-py==0.30.0
      - ruamel-yaml==0.19.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - setproctitle==1.3.7
      - setuptools==82.0.0
      - six==1.17.0
      - sklearn==0.0.post12
      - stack-data==0.6.3
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.3
      - traitlets==5.14.3
      - transforms3d==0.3.1
      - trimesh==4.11.1
      - triton==3.1.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - wcwidth==0.6.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - zipp==3.23.0
